# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [17]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

In [3]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'

In [4]:
pd.read_csv(url , sep = '\s+', parse_dates = [[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [5]:
data = pd.read_csv(url , sep = '\s+', parse_dates = [[0,1,2]])

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [6]:
def fix_century(x):
  year = x.year - 100 if x.year > 1989 else x.year
  return datetime.date(year, x.month, x.day)

data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_century)

data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [7]:
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].astype('datetime64[ns]')

In [8]:
data = data.set_index('Yr_Mo_Dy')

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [9]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [10]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [11]:
mean = data.mean()

In [12]:
mean = mean.mean()

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [13]:
loc_stats = data.describe()

In [14]:
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [15]:
day_stats = pd.DataFrame()

In [16]:
day_stats['Mean'] = data.mean(axis = 1)
day_stats['Maximum'] = data.max(axis = 1)
day_stats['Minimum'] = data.min(axis = 1)
day_stats['Standard deviations'] = data.std(axis = 1)

In [17]:
day_stats

                 Mean  Maximum  Minimum  Standard deviations
Yr_Mo_Dy
1961-01-01  13.018182    18.50     9.29             2.808875
1961-01-02  11.336364    17.54     6.50             3.188994
1961-01-03  11.641818    18.50     6.17             3.681912
1961-01-04   6.619167    11.75     1.79             3.198126
1961-01-05  10.630000    13.33     6.17             2.445356
...               ...      ...      ...                  ...
1978-12-27  16.708333    40.08     8.08             7.868076
1978-12-28  15.150000    41.46     5.00             9.687857
1978-12-29  14.890000    29.58     8.71             5.756836
1978-12-30  15.367500    28.79     9.13             5.540437
1978-12-31  15.402500    27.29     9.59             5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [18]:
data1 = data.loc[data.index.month == 1]

In [19]:
data1.mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [20]:
data.groupby(data.index.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [21]:
#Outra soluÃ§Ã£o
data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [22]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [23]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [24]:
data = data.iloc[1:]

In [26]:
data = data.resample('W').sum().agg(['min' , 'max' , 'mean' , 'std'], axis = 1)[:51]

In [27]:
data.loc["RPT":"MAL"]

DateParseError: Unknown datetime string format, unable to parse: RPT

In [114]:
data.groupby(data.index.to_period('W')).describe()[:51]

                        RPT                                               \
                      count       mean       std    min      25%     50%
Yr_Mo_Dy
1961-01-02/1961-01-08   6.0  13.346667  2.826656  10.58  11.5225  13.270
1961-01-09/1961-01-15   7.0  12.468571  3.555392   9.04  10.2500  12.040
1961-01-16/1961-01-22   7.0  13.204286  5.337402   4.92   9.5900  14.330
1961-01-23/1961-01-29   6.0  19.880000  4.619061  13.62  16.8225  19.855
1961-01-30/1961-02-05   7.0  16.827143  5.251408  10.58  13.2300  14.370
1961-02-06/1961-02-12   7.0  19.684286  3.587677  16.00  17.1000  18.050
1961-02-13/1961-02-19   7.0  15.130000  5.064609   6.04  13.6650  16.170
1961-02-20/1961-02-26   7.0  15.221429  7.020716   7.79   9.8750  12.290
1961-02-27/1961-03-05   7.0  12.101429  0.997721  10.96  11.1250  12.580
1961-03-06/1961-03-12   6.0   9.376667  3.732263   4.88   6.7300   9.085
1961-03-13/1961-03-19   7.0  11.911429  3.860036   4.92  11.1650  11.420
1961-03-20/1961-03-26   7.0   9.567143  3.613298   6.29   6.3600   9.540
1961-03-27/1961-04-02   7.0  10.757143  5.046922   5.88   8.0000   8.460
1961-04-03/1961-04-09   7.0  11.964286  4.604392   4.50   9.2750  13.370
1961-04-10/1961-04-16   7.0   8.965714  3.937727   4.71   5.4600  10.500
1961-04-17/1961-04-23   7.0  12.621429  5.676655   4.00   9.5000  12.210
1961-04-24/1961-04-30   7.0  10.117143  4.349662   4.08   7.5600   9.620
1961-05-01/1961-05-07   7.0  15.367143  5.025507   9.87  10.8150  15.870
1961-05-08/1961-05-14   7.0   7.772857  3.371022   3.54   5.4150   7.000
1961-05-15/1961-05-21   7.0   8.225714  3.631730   4.88   5.6050   6.830
1961-05-22/1961-05-28   7.0   8.155714  2.739433   4.96   5.8950   7.670
1961-05-29/1961-06-04   7.0  10.321429  3.099701   7.00   8.0000  10.000
1961-06-05/1961-06-11   7.0  10.917143  2.248597   8.29   9.0200  11.580
1961-06-12/1961-06-18   7.0  10.571429  3.009482   6.13   8.7900   9.960
1961-06-19/1961-06-25   7.0   7.345714  1.982035   4.00   6.0650   8.540
1961-06-26/1961-07-02   6.0  10.236667  2.557856   7.21   8.0625  10.520
1961-07-03/1961-07-09   7.0  11.715714  3.664855   7.29   9.5850  11.210
1961-07-10/1961-07-16   7.0  16.680000  5.168710   8.63  13.9150  16.920
1961-07-17/1961-07-23   7.0   4.202857  1.047978   3.04   3.3500   4.250
1961-07-24/1961-07-30   7.0  10.561429  4.157641   6.13   7.1050  10.130
1961-07-31/1961-08-06   7.0  10.870000  2.950887   7.67   8.9850  10.000
1961-08-07/1961-08-13   6.0  10.058333  4.422268   2.88   7.6500  11.835
1961-08-14/1961-08-20   7.0  15.607143  2.283635  13.13  13.6850  15.340
1961-08-21/1961-08-27   7.0  12.391429  3.395857   7.67  10.4350  12.380
1961-08-28/1961-09-03   7.0   8.678571  4.398615   3.63   5.2050   7.250
1961-09-04/1961-09-10   7.0  10.541429  5.207278   5.00   6.2700   9.210
1961-09-11/1961-09-17   7.0  17.160000  7.679190   5.33  13.2900  18.000
1961-09-18/1961-09-24   7.0   8.500000  1.267399   6.92   7.5400   8.500
1961-09-25/1961-10-01   7.0  16.044286  4.559572  10.34  12.7950  15.590
1961-10-02/1961-10-08   7.0  11.250000  5.596710   3.13   7.0200  14.090
1961-10-09/1961-10-15   6.0  10.881667  4.780675   3.71   8.4050  11.105
1961-10-16/1961-10-22   7.0  19.260000  7.888314  10.46  12.6250  17.120
1961-10-23/1961-10-29   7.0  16.077143  7.957637   4.33  11.3950  18.410
1961-10-30/1961-11-05   7.0  11.571429  3.369201   5.88   9.5850  13.210
1961-11-06/1961-11-12   7.0  10.428571  3.939811   5.46   7.8350   9.130
1961-11-13/1961-11-19   7.0  10.798571  2.784358   7.50   8.6450  10.670
1961-11-20/1961-11-26   7.0   9.154286  3.214368   5.75   6.3550   9.000
1961-11-27/1961-12-03   7.0  12.608571  5.704669   7.92   8.7500   9.670
1961-12-04/1961-12-10   7.0  17.362857  4.890152  10.83  14.2700  17.670
1961-12-11/1961-12-17   7.0  14.985714  4.095106   9.29  12.2550  15.460
1961-12-18/1961-12-24   7.0  15.757143  4.959717  11.46  12.2750  13.130

                                        VAL             ...     BEL         \
                           75%    max count       mean  ...     75%    max
Yr_Mo_Dy                                                ...
1961-01-02/1961-01-08  13.4575  18.50   6.0  11.486667  ...  13.700  16.62
1961-01-09/1961-01-15  12.9750  19.75   7.0   8.967143  ...  14.315  20.71
1961-01-16/1961-01-22  17.0850  19.83   7.0   9.862857  ...  11.960  15.92
1961-01-23/1961-01-29  23.7875  25.04   7.0  16.141429  ...  24.585  27.71
1961-01-30/1961-02-05  21.0850  24.21   7.0  15.460000  ...  17.690  19.33
1961-02-06/1961-02-12  22.5000  24.54   7.0  16.417143  ...  24.600  26.38
1961-02-13/1961-02-19  16.9350  22.50   7.0  15.091429  ...  25.270  29.63
1961-02-20/1961-02-26  20.4600  25.80   7.0  13.625714  ...  19.435  23.21
1961-02-27/1961-03-05  12.7950  13.33   7.0  12.951429  ...  20.310  23.45
1961-03-06/1961-03-12  11.6275  14.79   7.0  11.578571  ...  19.040  22.71
1961-03-13/1961-03-19  13.9150  16.88   7.0  13.501429  ...  21.125  22.79
1961-03-20/1961-03-26  11.7100  15.00   7.0   8.387143  ...  15.290  21.34
1961-03-27/1961-04-02  13.3550  18.25   7.0   8.852857  ...  16.915  18.63
1961-04-03/1961-04-09  14.6050  18.12   7.0  10.654286  ...  12.875  17.16
1961-04-10/1961-04-16  10.5650  15.50   7.0   8.000000  ...  10.585  16.17
1961-04-17/1961-04-23  16.0250  21.09   7.0  10.438571  ...  17.795  19.21
1961-04-24/1961-04-30  12.8550  16.29   7.0   9.798571  ...  12.190  13.04
1961-05-01/1961-05-07  18.6000  23.00   7.0  13.970000  ...  22.630  28.08
1961-05-08/1961-05-14  10.1250  12.79   7.0   8.712857  ...  10.875  18.66
1961-05-15/1961-05-21   9.8100  15.04   6.0   5.631667  ...  10.790  12.00
1961-05-22/1961-05-28  10.4400  11.79   7.0   7.388571  ...  12.835  14.33
1961-05-29/1961-06-04  11.6650  15.92   7.0   7.407143  ...  13.150  17.00
1961-06-05/1961-06-11  12.0450  14.42   7.0   8.992857  ...  12.335  16.17
1961-06-12/1961-06-18  13.0000  14.33   7.0   9.565714  ...  18.980  25.25
1961-06-19/1961-06-25   8.8750   9.00   7.0   6.108571  ...  14.835  19.08
1961-06-26/1961-07-02  12.2275  13.13   7.0   9.482857  ...  20.400  21.87
1961-07-03/1961-07-09  13.4200  17.50   7.0   7.220000  ...  13.900  20.41
1961-07-10/1961-07-16  20.4400  22.50   7.0  13.518571  ...  16.420  20.25
1961-07-17/1961-07-23   4.7750   5.88   7.0   4.255714  ...   8.895  10.13
1961-07-24/1961-07-30  13.6900  16.08   7.0   8.445714  ...  15.275  22.17
1961-07-31/1961-08-06  12.1850  16.08   7.0   8.792857  ...  15.725  18.54
1961-08-07/1961-08-13  12.9600  14.21   7.0   7.941429  ...  13.250  14.29
1961-08-14/1961-08-20  17.2500  18.91   7.0  10.565714  ...  16.395  21.92
1961-08-21/1961-08-27  13.8300  18.16   7.0  11.430000  ...  21.085  23.38
1961-08-28/1961-09-03  12.5000  14.46   7.0   8.821429  ...  18.955  24.71
1961-09-04/1961-09-10  14.7100  17.62   7.0   8.798571  ...  13.770  15.83
1961-09-11/1961-09-17  20.7300  28.75   7.0  14.440000  ...  23.680  23.91
1961-09-18/1961-09-24   9.3750  10.25   7.0   7.154286  ...  12.440  20.96
1961-09-25/1961-10-01  18.7900  23.21   6.0  11.361667  ...  20.235  21.37
1961-10-02/1961-10-08  15.7050  16.08   7.0   8.757143  ...  10.795  17.83
1961-10-09/1961-10-15  13.8350  17.12   7.0   9.734286  ...  17.100  20.46
1961-10-16/1961-10-22  26.6850  28.62   7.0  13.364286  ...  21.895  24.71
1961-10-23/1961-10-29  20.2950  26.42   7.0  11.867143  ...  19.705  27.29
1961-10-30/1961-11-05  13.4750  15.79   7.0   9.590000  ...  18.920  20.17
1961-11-06/1961-11-12  13.3300  16.08   7.0   7.690000  ...  11.060  12.58
1961-11-13/1961-11-19  12.5650  15.00   7.0   7.951429  ...   9.395   9.59
1961-11-20/1961-11-26  11.1650  14.29   7.0   7.337143  ...  15.040  20.46
1961-11-27/1961-12-03  14.7100  23.75   7.0  10.442857  ...  15.750  19.04
1961-12-04/1961-12-10  20.3950  23.71   7.0  14.362857  ...  19.855  21.79
1961-12-11/1961-12-17  17.1500  21.34   7.0  13.472857  ...  19.480  22.83
1961-12-18/1961-12-24  18.3750  24.41   7.0  11.971429  ...  13.875  17.67

                        MAL                                               \
                      count       mean       std    min      25%     50%
Yr_Mo_Dy
1961-01-02/1961-01-08   6.0  13.140000  1.921166  10.88  12.0500  12.940
1961-01-09/1961-01-15   7.0  11.024286  4.692355   5.17   6.8950  11.830
1961-01-16/1961-01-22   7.0  11.434286  4.237239   6.79   8.4350   9.920
1961-01-23/1961-01-29   7.0  22.530000  3.874721  17.50  19.3500  23.380
1961-01-30/1961-02-05   7.0  11.935714  4.336104   7.17   8.4150  11.710
1961-02-06/1961-02-12   7.0  19.155714  1.828705  17.04  17.6650  19.210
1961-02-13/1961-02-19   7.0  16.584286  4.685377  10.96  12.3350  17.670
1961-02-20/1961-02-26   7.0  14.322857  6.182283   6.67  10.6900  13.210
1961-02-27/1961-03-05   6.0  13.951667  3.021387   8.83  13.3250  13.895
1961-03-06/1961-03-12   7.0  14.420000  5.769890   5.54  11.1250  15.370
1961-03-13/1961-03-19   7.0  16.227143  4.331958  11.34  12.7700  15.710
1961-03-20/1961-03-26   7.0  18.134286  3.701846  13.13  15.1700  18.340
1961-03-27/1961-04-02   7.0  13.900000  3.924555   7.17  12.6050  13.170
1961-04-03/1961-04-09   7.0  11.371429  2.598271   7.21  10.2500  11.500
1961-04-10/1961-04-16   7.0   8.690000  2.747842   5.66   6.5850   7.710
1961-04-17/1961-04-23   7.0  12.470000  5.908542   4.96   8.9600  11.580
1961-04-24/1961-04-30   7.0   8.637143  5.108365   2.67   5.4800   8.460
1961-05-01/1961-05-07   7.0  14.571429  7.728504   3.83  11.6850  12.420
1961-05-08/1961-05-14   7.0  10.382857  7.858246   3.33   4.9200   9.500
1961-05-15/1961-05-21   7.0  10.612857  3.310819   5.91   8.3150  10.340
1961-05-22/1961-05-28   7.0  11.697143  3.811818   8.00   8.5250  10.920
1961-05-29/1961-06-04   7.0  13.597143  2.593586  10.63  11.7700  12.920
1961-06-05/1961-06-11   7.0  12.250000  4.925055   5.96   8.5400  12.290
1961-06-12/1961-06-18   7.0  15.025714  6.242673   6.13  11.5850  13.960
1961-06-19/1961-06-25   7.0  17.410000  3.063011  13.75  15.0400  16.880
1961-06-26/1961-07-02   6.0  12.133333  3.652313   8.50   9.2300  11.210
1961-07-03/1961-07-09   7.0  15.987143  3.665705  12.08  12.7100  16.040
1961-07-10/1961-07-16   7.0  12.524286  4.974273   5.96   9.9200  12.620
1961-07-17/1961-07-23   7.0   8.415714  2.133994   5.41   7.1450   8.330
1961-07-24/1961-07-30   7.0  13.761429  6.664574   6.13   9.2900  13.000
1961-07-31/1961-08-06   7.0  13.760000  4.448251   9.08  10.2300  11.870
1961-08-07/1961-08-13   7.0  10.125714  3.356585   5.88   7.6050  10.460
1961-08-14/1961-08-20   6.0  16.626667  3.934238  13.04  14.8625  15.835
1961-08-21/1961-08-27   7.0  16.485714  4.947608   8.29  13.9950  16.170
1961-08-28/1961-09-03   7.0  11.022857  6.308087   5.41   7.0400   8.000
1961-09-04/1961-09-10   7.0  11.034286  6.049619   3.37   6.3750  10.830
1961-09-11/1961-09-17   7.0  18.984286  6.332885  14.67  16.2100  16.750
1961-09-18/1961-09-24   7.0   9.814286  3.113507   5.25   8.1650   9.420
1961-09-25/1961-10-01   7.0  13.338571  4.696504   4.04  12.2100  15.710
1961-10-02/1961-10-08   7.0  11.410000  5.462002   4.83   7.4150   9.920
1961-10-09/1961-10-15   7.0  15.260000  4.098130  10.75  12.3950  12.870
1961-10-16/1961-10-22   7.0  23.641429  7.468377  13.46  19.1650  23.000
1961-10-23/1961-10-29   7.0  18.404286  8.340881   9.83  12.3550  13.290
1961-10-30/1961-11-05   7.0  19.195714  3.870800  13.37  16.8150  20.040
1961-11-06/1961-11-12   7.0  10.858571  3.690752   5.71   8.1700  11.460
1961-11-13/1961-11-19   7.0   5.737143  3.787654   2.00   3.1650   5.370
1961-11-20/1961-11-26   7.0  12.732857  6.475867   4.25   8.7100  10.340
1961-11-27/1961-12-03   7.0  14.725714  5.233192   5.88  12.3950  14.370
1961-12-04/1961-12-10   7.0  16.241429  7.345893   7.58  11.3750  15.410
1961-12-11/1961-12-17   7.0  14.644286  5.665006   6.50  11.1300  16.130
1961-12-18/1961-12-24   7.0   8.164286  5.048035   2.62   4.7900   5.910


                           75%    max
Yr_Mo_Dy
1961-01-02/1961-01-08  13.6350  16.46
1961-01-09/1961-01-15  14.7300  16.92
1961-01-16/1961-01-22  14.2500  17.96
1961-01-23/1961-01-29  25.2500  27.63
1961-01-30/1961-02-05  14.2950  19.25
1961-02-06/1961-02-12  20.3350  21.84
1961-02-13/1961-02-19  20.1050  22.58
1961-02-20/1961-02-26  17.5650  23.87
1961-02-27/1961-03-05  15.7850  17.54
1961-03-06/1961-03-12  17.6200  22.54
1961-03-13/1961-03-19  19.0250  22.95
1961-03-20/1961-03-26  21.3150  22.50
1961-03-27/1961-04-02  16.0850  19.58
1961-04-03/1961-04-09  12.5250  15.34
1961-04-10/1961-04-16  10.7100  12.87
1961-04-17/1961-04-23  16.1850  20.46
1961-04-24/1961-04-30  10.4350  17.50
1961-05-01/1961-05-07  17.9000  26.58
1961-05-08/1961-05-14  11.8550  26.30
1961-05-15/1961-05-21  13.2250  14.96
1961-05-22/1961-05-28  14.4350  17.04
1961-05-29/1961-06-04  15.0650  17.96
1961-06-05/1961-06-11  15.2950  19.83
1961-06-12/1961-06-18  18.6050  24.71
1961-06-19/1961-06-25  19.8300  21.50
1961-06-26/1961-07-02  15.1925  16.79
1961-07-03/1961-07-09  18.5400  21.29
1961-07-10/1961-07-16  13.6450  21.96
1961-07-17/1961-07-23   9.9800  10.92
1961-07-24/1961-07-30  16.6250  25.37
1961-07-31/1961-08-06  17.3300  20.25
1961-08-07/1961-08-13  12.0850  15.16
1961-08-14/1961-08-20  16.1175  24.30
1961-08-21/1961-08-27  20.3300  22.29
1961-08-28/1961-09-03  13.5650  22.54
1961-09-04/1961-09-10  15.0200  20.25
1961-09-11/1961-09-17  17.9800  33.09
1961-09-18/1961-09-24  11.5400  14.62
1961-09-25/1961-10-01  16.0200  17.16
1961-10-02/1961-10-08  15.3350  19.62
1961-10-09/1961-10-15  18.6850  21.04
1961-10-16/1961-10-22  28.6250  33.45
1961-10-23/1961-10-29  25.0600  30.88
1961-10-30/1961-11-05  21.8750  23.58
1961-11-06/1961-11-12  13.4800  15.54
1961-11-13/1961-11-19   6.6050  13.25
1961-11-20/1961-11-26  17.2700  22.58
1961-11-27/1961-12-03  18.3750  21.29
1961-12-04/1961-12-10  19.3100  29.33
1961-12-11/1961-12-17  18.2500  21.12
1961-12-18/1961-12-24  11.2100  16.62

[51 rows x 96 columns]